language: cpp
compiler:
  - gcc
os:
  - linux
  # - osx
osx_image: xcode12
addons:
  apt:
    packages:
      - libpng12-dev
before_script:
  - mkdir build
  - cd build
  - "if [ $TRAVIS_OS_NAME == osx ]; then \
        brew install imagemagick;
        cmake ..;
    fi"
  - curl -O -L https://github.com/Wargus/stratagus/archive/master.zip;
  - unzip master.zip;
  - cmake -DSTRATAGUS=stratagus -DSTRATAGUS_INCLUDE_DIR="$PWD/stratagus-master/gameheaders" ..;
script: make
after_success:
  - "if [ $TRAVIS_OS_NAME == osx ]; then \
        if [ $TRAVIS_REPO_SLUG == Wargus/war1gus -a \
             $TRAVIS_BRANCH == master -a \
             $TRAVIS_PULL_REQUEST == 'false' ]; then \
           cd $TRAVIS_BUILD_DIR;
           git clone https://${GH_TOKEN}@github.com/Wargus/stratagus.wiki.git;
           export STRATAGUS=$(pwd)/stratagus.wiki/$TRAVIS_OS_NAME/stratagus;
           mac/bundle.sh;
           tar czvf War1gus.app.tar.gz mac/War1gus.app;
           cp War1gus.app.tar.gz stratagus.wiki/$TRAVIS_OS_NAME/;
           cd stratagus.wiki/;
           git config --global user.email \"travis-ci@travis.org\";
           git config --global user.name \"Travis CI\";
           git add $TRAVIS_OS_NAME/War1gus.app.tar.gz;
           git commit --amend -C HEAD;
           git push -fq origin master;
           cd ..;
        fi;
    fi"

